"""Add Validation Engine models

Revision ID: 8b0852dc74d2
Revises: df87e8200ecb
Create Date: 2026-07-16 11:17:29.223235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b0852dc74d2'
down_revision: Union[str, None] = 'df87e8200ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('configurable_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_rules_code'), 'validation_rules', ['code'], unique=True)
    op.create_index(op.f('ix_validation_rules_id'), 'validation_rules', ['id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_celery_task_id'), 'validation_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_document_id'), 'validation_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_id'), 'validation_runs', ['id'], unique=False)
    op.create_table('quality_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('formatting_score', sa.Integer(), nullable=True),
    sa.Column('layout_score', sa.Integer(), nullable=True),
    sa.Column('typography_score', sa.Integer(), nullable=True),
    sa.Column('structure_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('publishing_readiness_score', sa.Integer(), nullable=True),
    sa.Column('overall_quality_score', sa.Integer(), nullable=True),
    sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_quality_scores_id'), 'quality_scores', ['id'], unique=False)
    op.create_table('validation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('total_issues', sa.Integer(), nullable=True),
    sa.Column('critical_issues', sa.Integer(), nullable=True),
    sa.Column('high_issues', sa.Integer(), nullable=True),
    sa.Column('medium_issues', sa.Integer(), nullable=True),
    sa.Column('low_issues', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_history_id'), 'validation_history', ['id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('problem', sa.String(), nullable=False),
    sa.Column('cause', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('auto_fix_possible', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    op.create_index(op.f('ix_validation_results_run_id'), 'validation_results', ['run_id'], unique=False)
    op.drop_index('ix_validation_reports_id', table_name='validation_reports')
    op.drop_table('validation_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['formatting_jobs.id'], name='validation_reports_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='validation_reports_pkey'),
    sa.UniqueConstraint('job_id', name='validation_reports_job_id_key')
    )
    op.create_index('ix_validation_reports_id', 'validation_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_validation_results_run_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_validation_history_id'), table_name='validation_history')
    op.drop_table('validation_history')
    op.drop_index(op.f('ix_quality_scores_id'), table_name='quality_scores')
    op.drop_table('quality_scores')
    op.drop_index(op.f('ix_validation_runs_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_document_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_celery_task_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_validation_rules_id'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_code'), table_name='validation_rules')
    op.drop_table('validation_rules')
    # ### end Alembic commands ###
