"""Refactor Template Schema to Blueprint

Revision ID: aace8f727934
Revises: fadd55713e28
Create Date: 2026-07-16 13:07:39.372032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aace8f727934'
down_revision: Union[str, None] = 'fadd55713e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprints_id'), 'blueprints', ['id'], unique=False)
    op.create_table('blueprint_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('blueprint_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprint_versions_id'), 'blueprint_versions', ['id'], unique=False)
    op.create_table('parsed_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('blueprint_layouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_version_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_version_id'], ['blueprint_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blueprint_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('rule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_version_id'], ['blueprint_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blueprint_styles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_version_id', sa.UUID(), nullable=False),
    sa.Column('style_name', sa.String(), nullable=False),
    sa.Column('style_type', sa.String(), nullable=False),
    sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_version_id'], ['blueprint_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprint_styles_style_name'), 'blueprint_styles', ['style_name'], unique=False)
    op.create_table('document_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parsed_document_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_metadata_key'), 'document_metadata', ['key'], unique=False)
    op.create_table('mapping_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('blueprint_version_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('book_type', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_version_id'], ['blueprint_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_profiles_id'), 'mapping_profiles', ['id'], unique=False)
    op.create_table('parsed_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parsed_document_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('element_type', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parsed_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_elements_element_type'), 'parsed_elements', ['element_type'], unique=False)
    op.create_table('document_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parsed_document_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['parsed_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parsed_document_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['parsed_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mapping_profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mapping_profile_id'], ['mapping_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('style_mappings', sa.Column('mapping_profile_id', sa.UUID(), nullable=False))
    op.add_column('style_mappings', sa.Column('blueprint_style_id', sa.UUID(), nullable=False))
    op.add_column('style_mappings', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('style_mappings', sa.Column('is_ai_suggested', sa.Boolean(), nullable=True))
    op.add_column('style_mappings', sa.Column('ai_reason', sa.String(), nullable=True))
    op.add_column('style_mappings', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.drop_constraint('style_mappings_template_style_id_fkey', 'style_mappings', type_='foreignkey')
    op.drop_constraint('style_mappings_template_version_id_fkey', 'style_mappings', type_='foreignkey')
    op.drop_index('ix_template_styles_style_name', table_name='template_styles')
    op.drop_table('template_styles')
    op.drop_table('formatting_rules')
    op.drop_table('template_versions')
    op.create_foreign_key(None, 'style_mappings', 'blueprint_styles', ['blueprint_style_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'style_mappings', 'mapping_profiles', ['mapping_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('style_mappings', 'template_style_id')
    op.drop_column('style_mappings', 'template_version_id')
    op.drop_column('style_mappings', 'is_override')
    op.add_column('templates', sa.Column('storage_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'storage_path')
    op.add_column('style_mappings', sa.Column('is_override', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('style_mappings', sa.Column('template_version_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('style_mappings', sa.Column('template_style_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'style_mappings', type_='foreignkey')
    op.drop_constraint(None, 'style_mappings', type_='foreignkey')
    op.create_foreign_key('style_mappings_template_version_id_fkey', 'style_mappings', 'template_versions', ['template_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('style_mappings_template_style_id_fkey', 'style_mappings', 'template_styles', ['template_style_id'], ['id'], ondelete='CASCADE')
    op.drop_column('style_mappings', 'is_approved')
    op.drop_column('style_mappings', 'ai_reason')
    op.drop_column('style_mappings', 'is_ai_suggested')
    op.drop_column('style_mappings', 'confidence')
    op.drop_column('style_mappings', 'blueprint_style_id')
    op.drop_column('style_mappings', 'mapping_profile_id')
    op.create_table('formatting_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rule_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], name='formatting_rules_template_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='formatting_rules_pkey')
    )
    op.create_table('template_styles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('style_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('style_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], name='template_styles_template_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='template_styles_pkey')
    )
    op.create_index('ix_template_styles_style_name', 'template_styles', ['style_name'], unique=False)
    op.create_table('template_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name='template_versions_template_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='template_versions_pkey')
    )
    op.drop_table('mapping_history')
    op.drop_table('document_tables')
    op.drop_table('document_images')
    op.drop_index(op.f('ix_parsed_elements_element_type'), table_name='parsed_elements')
    op.drop_table('parsed_elements')
    op.drop_index(op.f('ix_mapping_profiles_id'), table_name='mapping_profiles')
    op.drop_table('mapping_profiles')
    op.drop_index(op.f('ix_document_metadata_key'), table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_index(op.f('ix_blueprint_styles_style_name'), table_name='blueprint_styles')
    op.drop_table('blueprint_styles')
    op.drop_table('blueprint_rules')
    op.drop_table('blueprint_layouts')
    op.drop_table('parsed_documents')
    op.drop_index(op.f('ix_blueprint_versions_id'), table_name='blueprint_versions')
    op.drop_table('blueprint_versions')
    op.drop_index(op.f('ix_blueprints_id'), table_name='blueprints')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
