"""Add Export Engine models

Revision ID: cc00cffe4636
Revises: 8b0852dc74d2
Create Date: 2026-07-16 12:06:40.694086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc00cffe4636'
down_revision: Union[str, None] = '8b0852dc74d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('export_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_history_export_id'), 'download_history', ['export_id'], unique=False)
    op.create_index(op.f('ix_download_history_id'), 'download_history', ['id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('export_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_celery_task_id'), 'export_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_export_id'), 'export_jobs', ['export_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_id'), 'export_jobs', ['id'], unique=False)
    op.create_table('export_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('export_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_versions_document_id'), 'export_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_export_versions_id'), 'export_versions', ['id'], unique=False)
    op.add_column('exports', sa.Column('document_id', sa.UUID(), nullable=False))
    op.add_column('exports', sa.Column('checksum', sa.String(), nullable=True))
    op.add_column('exports', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('exports', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exports', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('exports', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('exports', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_exports_document_id'), 'exports', ['document_id'], unique=False)
    op.drop_constraint('exports_job_id_fkey', 'exports', type_='foreignkey')
    op.create_foreign_key(None, 'exports', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exports', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exports', sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.create_foreign_key('exports_job_id_fkey', 'exports', 'formatting_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_exports_document_id'), table_name='exports')
    op.alter_column('exports', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('exports', 'updated_at')
    op.drop_column('exports', 'created_at')
    op.drop_column('exports', 'metadata_json')
    op.drop_column('exports', 'file_size')
    op.drop_column('exports', 'checksum')
    op.drop_column('exports', 'document_id')
    op.drop_index(op.f('ix_export_versions_id'), table_name='export_versions')
    op.drop_index(op.f('ix_export_versions_document_id'), table_name='export_versions')
    op.drop_table('export_versions')
    op.drop_index(op.f('ix_export_jobs_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_export_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_celery_task_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_download_history_id'), table_name='download_history')
    op.drop_index(op.f('ix_download_history_export_id'), table_name='download_history')
    op.drop_table('download_history')
    # ### end Alembic commands ###
