"""Add AI models

Revision ID: df87e8200ecb
Revises: 9be41303b506
Create Date: 2026-07-16 11:07:52.375291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df87e8200ecb'
down_revision: Union[str, None] = '9be41303b506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('system_message', sa.String(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_id'), 'prompt_versions', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_name'), 'prompt_versions', ['name'], unique=False)
    op.create_table('ai_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_celery_task_id'), 'ai_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_id'), 'ai_jobs', ['id'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('total_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('total_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_id'), 'ai_usage', ['id'], unique=False)
    op.create_table('document_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('structure_tree', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('table_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_document_insights_id'), 'document_insights', ['id'], unique=False)
    op.create_table('ai_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_results_id'), 'ai_results', ['id'], unique=False)
    op.create_table('ai_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tokens_id'), 'ai_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tokens_id'), table_name='ai_tokens')
    op.drop_table('ai_tokens')
    op.drop_index(op.f('ix_ai_results_id'), table_name='ai_results')
    op.drop_table('ai_results')
    op.drop_index(op.f('ix_document_insights_id'), table_name='document_insights')
    op.drop_table('document_insights')
    op.drop_index(op.f('ix_ai_usage_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_ai_jobs_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_celery_task_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    op.drop_index(op.f('ix_prompt_versions_name'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
