from typing import List, Dict, Any
from app.services.export.engine import ExportRendererPlugin
from app.models.document_template import Document
from app.models.export import Export
import os

class MarkdownRenderer(ExportRendererPlugin):
    """Renders documents as Markdown."""
    
    @classmethod
    def get_supported_formats(cls) -> List[str]:
        return ["MARKDOWN", "MD"]

    def render(self, document: Document, export_record: Export, settings: Dict[str, Any]) -> str:
        # Mock rendering logic
        output_dir = f"/tmp/bookforge_exports/{document.id}"
        os.makedirs(output_dir, exist_ok=True)
        
        file_path = os.path.join(output_dir, f"{export_record.id}.md")
        
        content = f"# {document.title or 'Untitled Document'}\n\n"
        content += "This is a deterministic Markdown export generated by the Export Engine.\n"
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        return file_path
